include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Cirdock
Cirdock_FILES = /mnt/d/codes/cirdock/cirdockhooks/NSArray+LongestCommonSubsequence.m /mnt/d/codes/cirdock/cirdockhooks/iCarousel.m /mnt/d/codes/cirdock/cirdockhooks/UIAlertView+Blocks.m /mnt/d/codes/cirdock/cirdockhooks/Tweak.xm
Cirdock_FRAMEWORKS = UIKit QuartzCore CoreGraphics CydiaSubstrate
Cirdock_PRIVATE_FRAMEWORKS = AppSupport

export ARCHS = arm64
Cirdock_ARCHS = arm64
Cirdock_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
